{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 100000
     },
     "inputWidgets": {},
     "nuid": "1c408eb9-cbde-4b7a-9d3e-c02330dd1e8b",
     "showTitle": false,
     "tableResultSettingsMap": {
      "0": {
       "dataGridStateBlob": null,
       "filterBlob": "{\"version\":1,\"filterGroups\":[],\"syncTimestamp\":1785826642845}",
       "queryPlanFiltersBlob": "[]",
       "tableResultIndex": 0
      }
     },
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- Rule 1 (VUMC-specific database name): APPLIED\n",
    "-- Rule 2 (wildcard fix): NOT APPLICABLE\n",
    "-- Rule 3 (search concepts in clinical tables): APPLIED\n",
    "-- Rule 4 (LOINC/RxNorm/ICD code handling): APPLIED\n",
    "-- Rule 5 (free-text LIKE): NOT APPLICABLE\n",
    "-- Rule 6 (OR -> UNION): APPLIED\n",
    "-- Rule 7 (LEFT JOIN OR -> UNION): APPLIED\n",
    "-- Rule 8 (remove NLP): NOT APPLICABLE\n",
    "-- Rule 9 (mark missing concepts): NOT APPLICABLE\n",
    "-- FIX: Replaced correlated scalar subquery in JOIN with window function (ROW_NUMBER) in aki_blocks_ranked.\n",
    "-- FIX: Replaced (VALUES ...) blocks for esrd_dx, esrd_proc, and scr_lab with UNION ALL SELECT statements for Databricks compatibility.\n",
    "\n",
    "CREATE TABLE workspace_sdphenotypecore.phenotype_llm_logic.ex1_all_content_LLM1_AKI AS \n",
    "\n",
    "WITH\n",
    "-- 0.1  ESRD‑related diagnoses\n",
    "-- REVISED (was: SELECT concept_id FROM (VALUES ...))\n",
    "esrd_dx AS (\n",
    "    SELECT 45552870 AS concept_id UNION ALL\n",
    "    SELECT 45577822 UNION ALL\n",
    "    SELECT 45575617 UNION ALL\n",
    "    SELECT 45609389 UNION ALL\n",
    "    SELECT 45590127 UNION ALL\n",
    "    SELECT 45575620 UNION ALL\n",
    "    SELECT 45604584 UNION ALL\n",
    "    SELECT 35224814 UNION ALL\n",
    "    SELECT 1576113 UNION ALL\n",
    "    SELECT 1576114 UNION ALL\n",
    "    SELECT 45609945 UNION ALL\n",
    "    SELECT 44830633 UNION ALL\n",
    "    SELECT 44824846 UNION ALL\n",
    "    SELECT 44828407 UNION ALL\n",
    "    SELECT 44831843 UNION ALL\n",
    "    SELECT 44836535 UNION ALL\n",
    "    SELECT 44822716 UNION ALL\n",
    "    SELECT 44829650 UNION ALL\n",
    "    SELECT 44833130 UNION ALL\n",
    "    SELECT 44833131 UNION ALL\n",
    "    SELECT 44835496 UNION ALL\n",
    "    SELECT 44835497 UNION ALL\n",
    "    SELECT 44821578 UNION ALL\n",
    "    SELECT 44835472 UNION ALL\n",
    "    SELECT 44831947 UNION ALL\n",
    "    SELECT 44834280 UNION ALL\n",
    "    SELECT 1575308 UNION ALL\n",
    "    SELECT 45546763 UNION ALL\n",
    "    SELECT 45609393 UNION ALL\n",
    "    SELECT 45599829 UNION ALL\n",
    "    SELECT 45575625 UNION ALL\n",
    "    SELECT 45537090 UNION ALL\n",
    "    SELECT 4081759 UNION ALL\n",
    "    SELECT 42539502 UNION ALL\n",
    "    SELECT 199991 UNION ALL\n",
    "    SELECT 4128369 UNION ALL\n",
    "    SELECT 4127554\n",
    "),\n",
    "-- 0.2  ESRD‑related procedures / observations\n",
    "-- REVISED (was: SELECT concept_id FROM (VALUES ...))\n",
    "esrd_proc AS (\n",
    "    SELECT 2101833 AS concept_id UNION ALL\n",
    "    SELECT 2101834 UNION ALL\n",
    "    SELECT 2106278 UNION ALL\n",
    "    SELECT 42736574 UNION ALL\n",
    "    SELECT 2108276 UNION ALL\n",
    "    SELECT 2108277 UNION ALL\n",
    "    SELECT 2108297 UNION ALL\n",
    "    SELECT 2108299 UNION ALL\n",
    "    SELECT 2108302 UNION ALL\n",
    "    SELECT 42628575 UNION ALL\n",
    "    SELECT 42627979 UNION ALL\n",
    "    SELECT 42628018 UNION ALL\n",
    "    SELECT 42628576 UNION ALL\n",
    "    SELECT 42628058 UNION ALL\n",
    "    SELECT 42628580 UNION ALL\n",
    "    SELECT 2108564 UNION ALL\n",
    "    SELECT 2108566 UNION ALL\n",
    "    SELECT 2108567 UNION ALL\n",
    "    SELECT 2108568 UNION ALL\n",
    "    SELECT 2109463 UNION ALL\n",
    "    SELECT 2213572 UNION ALL\n",
    "    SELECT 2213573 UNION ALL\n",
    "    SELECT 2213575 UNION ALL\n",
    "    SELECT 2213576 UNION ALL\n",
    "    SELECT 2213577 UNION ALL\n",
    "    SELECT 2213578 UNION ALL\n",
    "    SELECT 2213579 UNION ALL\n",
    "    SELECT 2213580 UNION ALL\n",
    "    SELECT 2213581 UNION ALL\n",
    "    SELECT 2213582 UNION ALL\n",
    "    SELECT 2213583 UNION ALL\n",
    "    SELECT 2213584 UNION ALL\n",
    "    SELECT 2213585 UNION ALL\n",
    "    SELECT 2213586 UNION ALL\n",
    "    SELECT 2213587 UNION ALL\n",
    "    SELECT 2213588 UNION ALL\n",
    "    SELECT 2213589 UNION ALL\n",
    "    SELECT 2213590 UNION ALL\n",
    "    SELECT 2213591 UNION ALL\n",
    "    SELECT 2213592 UNION ALL\n",
    "    SELECT 2213593 UNION ALL\n",
    "    SELECT 2213594 UNION ALL\n",
    "    SELECT 2213595 UNION ALL\n",
    "    SELECT 2213596 UNION ALL\n",
    "    SELECT 2213597 UNION ALL\n",
    "    SELECT 2213598 UNION ALL\n",
    "    SELECT 2213599 UNION ALL\n",
    "    SELECT 2213600 UNION ALL\n",
    "    SELECT 2213601 UNION ALL\n",
    "    SELECT 2313999 UNION ALL\n",
    "    SELECT 2786488 UNION ALL\n",
    "    SELECT 4289454 UNION ALL\n",
    "    SELECT 4197217 UNION ALL\n",
    "    SELECT 4026915 UNION ALL\n",
    "    SELECT 4214705 UNION ALL\n",
    "    SELECT 4120120 UNION ALL\n",
    "    SELECT 4324124 UNION ALL\n",
    "    SELECT 2002176 UNION ALL\n",
    "    SELECT 2002189 UNION ALL\n",
    "    SELECT 2002208 UNION ALL\n",
    "    SELECT 2002209 UNION ALL\n",
    "    SELECT 2002282 UNION ALL\n",
    "    SELECT 2003564 UNION ALL\n",
    "    SELECT 2109586 UNION ALL\n",
    "    SELECT 2109587 UNION ALL\n",
    "    SELECT 2109589 UNION ALL\n",
    "    SELECT 2774517 UNION ALL\n",
    "    SELECT 2774518 UNION ALL\n",
    "    SELECT 2774519 UNION ALL\n",
    "    SELECT 2774520 UNION ALL\n",
    "    SELECT 2774521 UNION ALL\n",
    "    SELECT 2774522 UNION ALL\n",
    "    SELECT 4146256 UNION ALL\n",
    "    SELECT 4322471 UNION ALL\n",
    "    SELECT 2003622 UNION ALL\n",
    "    SELECT 2003624\n",
    "),\n",
    "-- 0.3  Serum‑creatinine measurement concepts (LOINC)\n",
    "-- REVISED (was: SELECT concept_id FROM (VALUES ...))\n",
    "scr_lab AS (\n",
    "    SELECT 3018968 AS concept_id UNION ALL\n",
    "    SELECT 3022243 UNION ALL\n",
    "    SELECT 3020564 UNION ALL\n",
    "    SELECT 3016723 UNION ALL\n",
    "    SELECT 3032033 UNION ALL\n",
    "    SELECT 3041716 UNION ALL\n",
    "    SELECT 3041735 UNION ALL\n",
    "    SELECT 3050951 UNION ALL\n",
    "    SELECT 40760920 UNION ALL\n",
    "    SELECT 40770372 UNION ALL\n",
    "    SELECT 43055236 UNION ALL\n",
    "    SELECT 44786911 UNION ALL\n",
    "    SELECT 46235076\n",
    "),\n",
    "-- 1. Candidate presentation windows (ED + IP visits)\n",
    "candidate_visits AS (\n",
    "    SELECT  person_id,\n",
    "            visit_occurrence_id,\n",
    "            visit_start_date,\n",
    "            visit_end_date\n",
    "    FROM    victr_sd.sd_omop_prod.visit_occurrence\n",
    "    WHERE   visit_concept_id IN (262, 9201)\n",
    "),\n",
    "-- 2. ESRD history exclusion\n",
    "excluded_esrd AS (\n",
    "    SELECT DISTINCT person_id, visit_occurrence_id\n",
    "    FROM (\n",
    "        SELECT cv.person_id, cv.visit_occurrence_id\n",
    "        FROM candidate_visits cv\n",
    "        JOIN victr_sd.sd_omop_prod.condition_occurrence co\n",
    "          ON co.person_id=cv.person_id\n",
    "         AND co.condition_concept_id IN (SELECT concept_id FROM esrd_dx)\n",
    "         AND co.condition_start_date < cv.visit_start_date\n",
    "        UNION\n",
    "        SELECT cv.person_id, cv.visit_occurrence_id\n",
    "        FROM candidate_visits cv\n",
    "        JOIN victr_sd.sd_omop_prod.procedure_occurrence po\n",
    "          ON po.person_id=cv.person_id\n",
    "         AND po.procedure_concept_id IN (SELECT concept_id FROM esrd_proc)\n",
    "         AND po.procedure_date < cv.visit_start_date\n",
    "    ) esrd_union\n",
    "),\n",
    "-- 3. Three‑tier baseline SCr\n",
    "baseline_t1 AS (\n",
    "    SELECT  cv.person_id,\n",
    "            cv.visit_occurrence_id,\n",
    "            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY m.value_as_number)\n",
    "            AS baseline_scr\n",
    "    FROM    candidate_visits cv\n",
    "    JOIN    victr_sd.sd_omop_prod.measurement m\n",
    "           ON m.person_id=cv.person_id\n",
    "    JOIN    scr_lab l\n",
    "           ON m.measurement_concept_id = l.concept_id\n",
    "          AND m.value_as_number IS NOT NULL\n",
    "          AND m.measurement_date BETWEEN cv.visit_start_date - INTERVAL 365 DAYS\n",
    "                                     AND cv.visit_start_date - INTERVAL 7 DAYS\n",
    "    GROUP BY cv.person_id, cv.visit_occurrence_id\n",
    "),\n",
    "baseline_t2 AS (\n",
    "    SELECT  cv.person_id,\n",
    "            cv.visit_occurrence_id,\n",
    "            MIN(m.value_as_number) AS baseline_scr\n",
    "    FROM    candidate_visits cv\n",
    "    JOIN    victr_sd.sd_omop_prod.measurement m\n",
    "           ON m.person_id=cv.person_id\n",
    "    JOIN    scr_lab l\n",
    "           ON m.measurement_concept_id = l.concept_id\n",
    "          AND m.value_as_number IS NOT NULL\n",
    "          AND m.measurement_date BETWEEN cv.visit_start_date - INTERVAL 7 DAYS\n",
    "                                     AND cv.visit_start_date\n",
    "    WHERE  NOT EXISTS (SELECT 1\n",
    "                       FROM   baseline_t1 b1\n",
    "                       WHERE  b1.person_id=cv.person_id\n",
    "                         AND  b1.visit_occurrence_id=cv.visit_occurrence_id)\n",
    "    GROUP BY cv.person_id, cv.visit_occurrence_id\n",
    "),\n",
    "baseline_t3 AS (\n",
    "    SELECT  cv.person_id,\n",
    "            cv.visit_occurrence_id,\n",
    "            MIN(m.value_as_number) AS baseline_scr\n",
    "    FROM    candidate_visits cv\n",
    "    JOIN    victr_sd.sd_omop_prod.measurement m\n",
    "           ON m.person_id=cv.person_id\n",
    "    JOIN    scr_lab l\n",
    "           ON m.measurement_concept_id = l.concept_id\n",
    "          AND m.value_as_number IS NOT NULL\n",
    "          AND m.measurement_date >= cv.visit_start_date\n",
    "    WHERE  NOT EXISTS (SELECT 1\n",
    "                       FROM   baseline_t1 b1\n",
    "                       WHERE  b1.person_id=cv.person_id\n",
    "                         AND  b1.visit_occurrence_id=cv.visit_occurrence_id)\n",
    "      AND  NOT EXISTS (SELECT 1\n",
    "                       FROM   baseline_t2 b2\n",
    "                       WHERE  b2.person_id=cv.person_id\n",
    "                         AND  b2.visit_occurrence_id=cv.visit_occurrence_id)\n",
    "    GROUP BY cv.person_id, cv.visit_occurrence_id\n",
    "),\n",
    "baseline_scr AS (\n",
    "    SELECT * FROM baseline_t1\n",
    "    UNION ALL\n",
    "    SELECT * FROM baseline_t2\n",
    "    UNION ALL\n",
    "    SELECT * FROM baseline_t3\n",
    "),\n",
    "-- 4. Daily kidney‑function assessment\n",
    "daily_scr AS (\n",
    "    SELECT  m.person_id,\n",
    "            m.visit_occurrence_id,\n",
    "            m.measurement_date,\n",
    "            ROUND(AVG(m.value_as_number),3) AS mean_scr\n",
    "    FROM    victr_sd.sd_omop_prod.measurement m\n",
    "    JOIN    candidate_visits cv\n",
    "           ON cv.person_id           = m.person_id\n",
    "          AND cv.visit_occurrence_id = m.visit_occurrence_id\n",
    "    JOIN    scr_lab l\n",
    "           ON m.measurement_concept_id = l.concept_id\n",
    "    WHERE   m.value_as_number IS NOT NULL\n",
    "    GROUP BY m.person_id, m.visit_occurrence_id, m.measurement_date\n",
    "),\n",
    "daily_ratio AS (\n",
    "    SELECT  ds.*,\n",
    "            try_divide(ds.mean_scr,bs.baseline_scr)                  AS scr_ratio,\n",
    "            CASE WHEN try_divide(ds.mean_scr,bs.baseline_scr) >= 1.5 THEN 1 ELSE 0 END AS abnormal_flag\n",
    "    FROM    daily_scr  ds\n",
    "    JOIN    baseline_scr bs\n",
    "           ON bs.person_id=ds.person_id\n",
    "          AND bs.visit_occurrence_id=ds.visit_occurrence_id\n",
    "),\n",
    "-- 5. AKI status per visit\n",
    "aki_status AS (\n",
    "    SELECT  cv.person_id,\n",
    "            cv.visit_occurrence_id,\n",
    "            CASE\n",
    "                WHEN bs.baseline_scr IS NULL\n",
    "                     OR NOT EXISTS (\n",
    "                          SELECT 1 FROM daily_ratio dr\n",
    "                          WHERE  dr.person_id=cv.person_id\n",
    "                            AND  dr.visit_occurrence_id=cv.visit_occurrence_id)\n",
    "                     THEN 'AKI_UNKNOWN'\n",
    "                WHEN NOT EXISTS (\n",
    "                          SELECT 1 FROM daily_ratio dr\n",
    "                          WHERE  dr.person_id=cv.person_id\n",
    "                            AND  dr.visit_occurrence_id=cv.visit_occurrence_id\n",
    "                            AND  dr.abnormal_flag=1)\n",
    "                     THEN 'AKI_NO'\n",
    "                ELSE 'AKI_YES'\n",
    "            END AS aki_status\n",
    "    FROM    candidate_visits cv\n",
    "    LEFT    JOIN baseline_scr bs\n",
    "           ON bs.person_id=cv.person_id\n",
    "          AND bs.visit_occurrence_id=cv.visit_occurrence_id\n",
    "),\n",
    "-- 6. AKI blocks, stage, subtype, recurrence\n",
    "abn_days AS (\n",
    "    SELECT  dr.*,\n",
    "            LAG(dr.measurement_date) OVER (\n",
    "                PARTITION BY dr.person_id, dr.visit_occurrence_id\n",
    "                ORDER BY     dr.measurement_date)                      AS prev_abn_date\n",
    "    FROM    daily_ratio dr\n",
    "    WHERE   dr.abnormal_flag = 1\n",
    "),\n",
    "abn_days_flagged AS (\n",
    "    SELECT  *,\n",
    "            CASE\n",
    "                WHEN prev_abn_date IS NULL\n",
    "                     OR DATEDIFF(measurement_date, prev_abn_date) > 2\n",
    "                     THEN 1 ELSE 0\n",
    "            END AS new_block_flag\n",
    "    FROM    abn_days\n",
    "),\n",
    "abn_days_grouped AS (\n",
    "    SELECT  *,\n",
    "            SUM(new_block_flag) OVER (\n",
    "                PARTITION BY person_id, visit_occurrence_id\n",
    "                ORDER BY     measurement_date)                        AS grp\n",
    "    FROM    abn_days_flagged\n",
    "),\n",
    "aki_blocks AS (\n",
    "    SELECT  person_id,\n",
    "            visit_occurrence_id,\n",
    "            MIN(measurement_date)                          AS block_start,\n",
    "            MAX(measurement_date)                          AS block_end,\n",
    "            COUNT(*)                                       AS block_days,\n",
    "            MAX(scr_ratio)                                 AS max_ratio\n",
    "    FROM    abn_days_grouped\n",
    "    GROUP BY person_id, visit_occurrence_id, grp\n",
    "),\n",
    "aki_blocks_enhanced AS (\n",
    "    SELECT  *,\n",
    "            CASE WHEN max_ratio < 2.0  THEN 1\n",
    "                 WHEN max_ratio <= 3.0 THEN 2\n",
    "                 ELSE                      3 END          AS akin_stage,\n",
    "            CASE WHEN block_days < 2   THEN 'tAKI'\n",
    "                 ELSE                     'sAKI' END      AS aki_subtype\n",
    "    FROM    aki_blocks\n",
    "),\n",
    "aki_blocks_ranked AS (\n",
    "    SELECT *,\n",
    "           ROW_NUMBER() OVER (PARTITION BY person_id, visit_occurrence_id ORDER BY block_start ASC) AS rn\n",
    "    FROM aki_blocks_enhanced\n",
    "),\n",
    "aki_rec AS (\n",
    "    SELECT  person_id,\n",
    "            visit_occurrence_id,\n",
    "            COUNT(*) AS total_blocks\n",
    "    FROM    aki_blocks\n",
    "    GROUP BY person_id, visit_occurrence_id\n",
    "),\n",
    "-- 7. Final cohort  (cases & controls, ESRD‑free)\n",
    "final_aki AS (\n",
    "    SELECT  cv.person_id,\n",
    "            cv.visit_occurrence_id,\n",
    "            a.aki_status,\n",
    "            CASE WHEN a.aki_status='AKI_YES' THEN 'CASE'\n",
    "                 WHEN a.aki_status='AKI_NO'  THEN 'CONTROL'\n",
    "                 ELSE NULL END                      AS case_control_flag,\n",
    "            ab.block_start,\n",
    "            ab.block_end,\n",
    "            ab.akin_stage,\n",
    "            ab.aki_subtype,\n",
    "            ar.total_blocks\n",
    "    FROM    candidate_visits cv\n",
    "    LEFT    JOIN excluded_esrd ex\n",
    "           ON ex.person_id=cv.person_id\n",
    "          AND ex.visit_occurrence_id=cv.visit_occurrence_id\n",
    "    JOIN    aki_status a\n",
    "           ON a.person_id=cv.person_id\n",
    "          AND a.visit_occurrence_id=cv.visit_occurrence_id\n",
    "    LEFT    JOIN aki_blocks_ranked ab\n",
    "           ON ab.person_id=cv.person_id\n",
    "          AND ab.visit_occurrence_id=cv.visit_occurrence_id\n",
    "          AND ab.rn = 1\n",
    "    LEFT    JOIN aki_rec ar\n",
    "           ON ar.person_id=cv.person_id\n",
    "          AND ar.visit_occurrence_id=cv.visit_occurrence_id\n",
    "    WHERE   ex.person_id IS NULL\n",
    ")\n",
    "SELECT *\n",
    "FROM   final_aki;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": false,
     "catalog": "workspace_sdphenotypecore",
     "schema": "agd_flagship"
    }
   },
   "notebookName": "ex1_all_content__LLM1__AKI.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}