{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 100000
     },
     "inputWidgets": {},
     "nuid": "506af55e-d41c-47d9-a26e-d2b067f26a9c",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- Rule 1 (VUMC-specific database name): APPLIED\n",
    "-- Rule 4 (LOINC/RxNorm code handling): APPLIED\n",
    "-- Rule 5 (Local names/descriptions): NOT APPLICABLE (no free-text name filters)\n",
    "-- Rule 6 (OR -> UNION): APPLIED (for flagged_patients)\n",
    "-- Rule 2 (wildcard): NOT APPLICABLE\n",
    "-- Rule 3 (searching for concepts): APPLIED (measurement_concept_id and drug_concept_id)\n",
    "-- Rule 7 (LEFT JOIN -> UNION): APPLIED (flagged_patients)\n",
    "-- Rule 8 (NLP logic): NOT APPLICABLE\n",
    "-- Rule 9 (missing concept): NOT APPLICABLE\n",
    "\n",
    "CREATE TABLE workspace_sdphenotypecore.phenotype_llm_logic.ex2_only_text_LLM2_FH AS \n",
    "\n",
    "WITH \n",
    "-- REVISED (was: FROM measurement m)\n",
    "ldl_calculations AS (\n",
    "    SELECT \n",
    "        m.person_id,\n",
    "        m.measurement_date,\n",
    "        p.year_of_birth,\n",
    "        p.gender_concept_id,\n",
    "        MAX(CASE \n",
    "            WHEN c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3028288', '3001308', '3033638', '3002089') THEN m.value_as_number \n",
    "        END) AS ldl_direct,\n",
    "        MAX(CASE \n",
    "            WHEN c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3027114', '3019900') THEN m.value_as_number \n",
    "        END) AS total_chol,\n",
    "        MAX(CASE \n",
    "            WHEN c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3023103', '3007070') THEN m.value_as_number \n",
    "        END) AS hdl_chol,\n",
    "        MAX(CASE \n",
    "            WHEN c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3022038', '3019747') THEN m.value_as_number \n",
    "        END) AS triglycerides\n",
    "    FROM victr_sd.sd_omop_prod.measurement m\n",
    "    INNER JOIN victr_sd.sd_omop_prod.concept c ON m.measurement_concept_id = c.concept_id -- Rule 4\n",
    "    INNER JOIN victr_sd.sd_omop_prod.person p ON m.person_id = p.person_id -- Rule 1\n",
    "    WHERE m.value_as_number IS NOT NULL \n",
    "        AND m.value_as_number > 0\n",
    "        AND EXTRACT(YEAR FROM m.measurement_date) - p.year_of_birth >= 18\n",
    "    GROUP BY m.person_id, m.measurement_date, p.year_of_birth, p.gender_concept_id\n",
    "),\n",
    "\n",
    "eligible_patients AS (\n",
    "    SELECT \n",
    "        person_id,\n",
    "        year_of_birth,\n",
    "        gender_concept_id,\n",
    "        measurement_date AS index_date,\n",
    "        COALESCE(\n",
    "            ldl_direct,\n",
    "            CASE \n",
    "                WHEN total_chol IS NOT NULL \n",
    "                    AND hdl_chol IS NOT NULL \n",
    "                    AND triglycerides IS NOT NULL \n",
    "                    AND triglycerides < 400  \n",
    "                THEN total_chol - hdl_chol - (try_divide(triglycerides,5.0))\n",
    "            END\n",
    "        ) AS ldl_c_value,\n",
    "        triglycerides,\n",
    "        ROW_NUMBER() OVER (\n",
    "            PARTITION BY person_id \n",
    "            ORDER BY COALESCE(\n",
    "                ldl_direct,\n",
    "                CASE \n",
    "                    WHEN total_chol IS NOT NULL AND hdl_chol IS NOT NULL \n",
    "                        AND triglycerides IS NOT NULL AND triglycerides < 400\n",
    "                    THEN total_chol - hdl_chol - (try_divide(triglycerides,5.0))\n",
    "                END\n",
    "            ) DESC NULLS LAST\n",
    "        ) AS rn\n",
    "    FROM ldl_calculations\n",
    "    WHERE COALESCE(\n",
    "        ldl_direct,\n",
    "        CASE \n",
    "            WHEN total_chol IS NOT NULL AND hdl_chol IS NOT NULL \n",
    "                AND triglycerides IS NOT NULL AND triglycerides < 400\n",
    "            THEN total_chol - hdl_chol - (try_divide(triglycerides,5.0))\n",
    "        END\n",
    "    ) IS NOT NULL\n",
    "),\n",
    "\n",
    "patients_with_index AS (\n",
    "    SELECT *\n",
    "    FROM eligible_patients\n",
    "    WHERE rn = 1\n",
    "),\n",
    "\n",
    "-- REVISED (was: AND de.drug_concept_id IN (...))\n",
    "ldl_adjusted AS (\n",
    "    SELECT \n",
    "        p.person_id,\n",
    "        p.year_of_birth,\n",
    "        p.gender_concept_id,\n",
    "        p.index_date,\n",
    "        p.ldl_c_value AS original_ldl_c,\n",
    "        p.triglycerides,\n",
    "        CASE \n",
    "            WHEN EXISTS (\n",
    "                SELECT 1 FROM victr_sd.sd_omop_prod.drug_exposure de\n",
    "                INNER JOIN victr_sd.sd_omop_prod.concept_ancestor ca ON ca.descendant_concept_id = de.drug_concept_id -- Rule 4\n",
    "                INNER JOIN victr_sd.sd_omop_prod.concept c ON ca.ancestor_concept_id = c.concept_id -- Rule 4\n",
    "                WHERE de.person_id = p.person_id\n",
    "                    AND c.vocabulary_id = 'RxNorm' AND c.concept_code IN (\n",
    "                        '1539403', '1549686', '1592085', '1545958', '1510813',\n",
    "                        '1549683', '1539463', '1551803', '1510831',\n",
    "                        '1551860', '1551885', '1558254',\n",
    "                        '1549785', '1549687', '1539462',\n",
    "                        '40165636', '40165638',\n",
    "                        '1545149', '1551099', '1539411',\n",
    "                        '1510240', '1539418',\n",
    "                        '1304377', '1308738',\n",
    "                        '1350489',\n",
    "                        '1341268',\n",
    "                        '956874', '950637',\n",
    "                        '1301267',\n",
    "                        '1392427',\n",
    "                        '1363053',\n",
    "                        '40166035',\n",
    "                        '42628089',\n",
    "                        '44785829', '44816332'\n",
    "                    )\n",
    "                    AND de.drug_exposure_start_date BETWEEN p.index_date - INTERVAL 1 YEAR AND p.index_date\n",
    "            )\n",
    "            THEN try_divide(p.ldl_c_value,0.7)\n",
    "            ELSE p.ldl_c_value\n",
    "        END AS adjusted_ldl_c\n",
    "    FROM patients_with_index p\n",
    "),\n",
    "\n",
    "-- REVISED (was: measurement_concept_id IN (...))\n",
    "secondary_causes AS (\n",
    "    SELECT DISTINCT la.person_id\n",
    "    FROM ldl_adjusted la\n",
    "    WHERE EXISTS (\n",
    "        SELECT 1 FROM victr_sd.sd_omop_prod.measurement m\n",
    "        INNER JOIN victr_sd.sd_omop_prod.concept c ON m.measurement_concept_id = c.concept_id -- Rule 4\n",
    "        WHERE m.person_id = la.person_id\n",
    "            AND m.measurement_date BETWEEN la.index_date - INTERVAL 1 YEAR AND la.index_date\n",
    "            AND (\n",
    "                (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3016431', '3020564') AND m.value_as_number >= 10)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3035995', '3004501') AND m.value_as_number >= 200)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3024128', '3013721') AND m.value_as_number > 2.0)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3014051', '3037110') AND m.value_as_number > 3000)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3021162', '3020630') AND m.value_as_number > 3.0)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3016723', '3051825') AND m.value_as_number > 2.6)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3049187', '3053283', '3030354') AND m.value_as_number < 15)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3004410', '3003309', '40758583') AND m.value_as_number > 9)\n",
    "                OR (c.vocabulary_id = 'LOINC' AND c.concept_code IN ('3037110', '3004501') AND m.value_as_number > 200)\n",
    "            )\n",
    "    )\n",
    "),\n",
    "\n",
    "-- REVISED (was: OR logic for flagged_patients)\n",
    "flagged_patients AS (\n",
    "    SELECT DISTINCT person_id\n",
    "    FROM (\n",
    "        SELECT person_id \n",
    "        FROM ldl_adjusted\n",
    "        WHERE triglycerides > 220\n",
    "        UNION\n",
    "        SELECT la.person_id\n",
    "        FROM ldl_adjusted la\n",
    "        WHERE EXISTS (\n",
    "            SELECT 1 FROM victr_sd.sd_omop_prod.condition_occurrence co\n",
    "            WHERE co.person_id = la.person_id\n",
    "                AND co.condition_concept_id IN (\n",
    "                    433260, 4299535, 4013978, 4218674, 4132711\n",
    "                )\n",
    "                AND co.condition_start_date BETWEEN la.index_date - INTERVAL 1 YEAR AND la.index_date\n",
    "        )\n",
    "    ) f\n",
    "),\n",
    "\n",
    "primary_hypercholesterolemia AS (\n",
    "    SELECT \n",
    "        la.person_id,\n",
    "        la.year_of_birth,\n",
    "        la.gender_concept_id,\n",
    "        la.index_date,\n",
    "        la.original_ldl_c,\n",
    "        la.adjusted_ldl_c,\n",
    "        CASE \n",
    "            WHEN la.adjusted_ldl_c >= 155 \n",
    "                AND sc.person_id IS NULL \n",
    "                AND fp.person_id IS NULL \n",
    "            THEN 'CASE'\n",
    "            WHEN la.adjusted_ldl_c < 155 \n",
    "            THEN 'CONTROL'\n",
    "            ELSE 'EXCLUDED'\n",
    "        END AS stage1_status\n",
    "    FROM ldl_adjusted la\n",
    "    LEFT JOIN secondary_causes sc ON la.person_id = sc.person_id\n",
    "    LEFT JOIN flagged_patients fp ON la.person_id = fp.person_id\n",
    "),\n",
    "\n",
    "ldl_score AS (\n",
    "    SELECT \n",
    "        person_id,\n",
    "        CASE \n",
    "            WHEN adjusted_ldl_c >= 330 THEN 8\n",
    "            WHEN adjusted_ldl_c >= 250 THEN 5  \n",
    "            WHEN adjusted_ldl_c >= 190 THEN 3\n",
    "            WHEN adjusted_ldl_c >= 155 THEN 1\n",
    "            ELSE 0\n",
    "        END AS ldl_points\n",
    "    FROM primary_hypercholesterolemia\n",
    "    WHERE stage1_status = 'CASE'\n",
    "),\n",
    "\n",
    "family_ascvd_score AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        MAX(CASE \n",
    "            WHEN o.observation_concept_id IN (\n",
    "                4167217, 4165588, 4212999, 4051114\n",
    "            ) THEN 1\n",
    "            ELSE 0\n",
    "        END) AS family_ascvd_points\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN victr_sd.sd_omop_prod.observation o ON ph.person_id = o.person_id -- Rule 1\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    "    GROUP BY ph.person_id\n",
    "),\n",
    "\n",
    "family_chol_score AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        MAX(CASE \n",
    "            WHEN o.observation_concept_id IN (\n",
    "                4167191, 40479314\n",
    "            ) THEN 1\n",
    "            ELSE 0\n",
    "        END) AS family_chol_points\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN victr_sd.sd_omop_prod.observation o ON ph.person_id = o.person_id -- Rule 1\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    "    GROUP BY ph.person_id\n",
    "),\n",
    "\n",
    "personal_chd_score AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        MAX(CASE \n",
    "            WHEN co.condition_concept_id IN (\n",
    "                4329847, 314666, 312327, 434376, 438447, 444406,\n",
    "                321318, 317576, 318443, 77670,\n",
    "                317576, 764123, 46273477, 4324693,\n",
    "                314378, 321886, 324203\n",
    "            )\n",
    "            AND (\n",
    "                (ph.gender_concept_id = 8507 AND EXTRACT(YEAR FROM co.condition_start_date) - ph.year_of_birth < 56)\n",
    "                OR \n",
    "                (ph.gender_concept_id = 8532 AND EXTRACT(YEAR FROM co.condition_start_date) - ph.year_of_birth < 66)\n",
    "            )\n",
    "            THEN 2\n",
    "            ELSE 0\n",
    "        END) AS personal_chd_points\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN victr_sd.sd_omop_prod.condition_occurrence co ON ph.person_id = co.person_id -- Rule 1\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    "    GROUP BY ph.person_id, ph.gender_concept_id, ph.year_of_birth\n",
    "),\n",
    "\n",
    "personal_cvd_pad_score AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        MAX(CASE \n",
    "            WHEN co.condition_concept_id IN (\n",
    "                372924, 381591, 443454, 312939, 373503, 376713, 432923,\n",
    "                321052, 4313767, 195834, 317309, 318072\n",
    "            )\n",
    "            AND (\n",
    "                (ph.gender_concept_id = 8507 AND EXTRACT(YEAR FROM co.condition_start_date) - ph.year_of_birth < 56)\n",
    "                OR \n",
    "                (ph.gender_concept_id = 8532 AND EXTRACT(YEAR FROM co.condition_start_date) - ph.year_of_birth < 66)\n",
    "            )\n",
    "            THEN 1\n",
    "            ELSE 0\n",
    "        END) AS personal_cvd_pad_points\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN victr_sd.sd_omop_prod.condition_occurrence co ON ph.person_id = co.person_id -- Rule 1\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    "    GROUP BY ph.person_id, ph.gender_concept_id, ph.year_of_birth\n",
    "),\n",
    "\n",
    "xanthoma_score AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        MAX(CASE \n",
    "            WHEN co.condition_concept_id IN (\n",
    "                4103295, 4079843, 133444\n",
    "            ) THEN 6  \n",
    "            ELSE 0\n",
    "        END) AS xanthoma_points\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN victr_sd.sd_omop_prod.condition_occurrence co ON ph.person_id = co.person_id -- Rule 1\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    "    GROUP BY ph.person_id\n",
    "),\n",
    "\n",
    "arcus_score AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        MAX(CASE \n",
    "            WHEN co.condition_concept_id IN (\n",
    "                4038838, 373425\n",
    "            )\n",
    "            AND EXTRACT(YEAR FROM co.condition_start_date) - ph.year_of_birth < 45\n",
    "            THEN 4\n",
    "            ELSE 0\n",
    "        END) AS arcus_points\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN victr_sd.sd_omop_prod.condition_occurrence co ON ph.person_id = co.person_id -- Rule 1\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    "    GROUP BY ph.person_id, ph.year_of_birth\n",
    "),\n",
    "\n",
    "dlcn_total_scores AS (\n",
    "    SELECT \n",
    "        ph.person_id,\n",
    "        ph.index_date,\n",
    "        ph.original_ldl_c,\n",
    "        ph.adjusted_ldl_c,\n",
    "        COALESCE(ls.ldl_points, 0) AS ldl_points,\n",
    "        COALESCE(fa.family_ascvd_points, 0) AS family_ascvd_points,\n",
    "        COALESCE(fc.family_chol_points, 0) AS family_chol_points,\n",
    "        COALESCE(pc.personal_chd_points, 0) AS personal_chd_points,\n",
    "        COALESCE(pcv.personal_cvd_pad_points, 0) AS personal_cvd_pad_points,\n",
    "        COALESCE(x.xanthoma_points, 0) AS xanthoma_points,\n",
    "        COALESCE(a.arcus_points, 0) AS arcus_points,\n",
    "        (COALESCE(ls.ldl_points, 0) + \n",
    "         COALESCE(fa.family_ascvd_points, 0) + \n",
    "         COALESCE(fc.family_chol_points, 0) + \n",
    "         COALESCE(pc.personal_chd_points, 0) + \n",
    "         COALESCE(pcv.personal_cvd_pad_points, 0) + \n",
    "         COALESCE(x.xanthoma_points, 0) + \n",
    "         COALESCE(a.arcus_points, 0)) AS total_dlcn_score\n",
    "    FROM primary_hypercholesterolemia ph\n",
    "    LEFT JOIN ldl_score ls ON ph.person_id = ls.person_id\n",
    "    LEFT JOIN family_ascvd_score fa ON ph.person_id = fa.person_id\n",
    "    LEFT JOIN family_chol_score fc ON ph.person_id = fc.person_id\n",
    "    LEFT JOIN personal_chd_score pc ON ph.person_id = pc.person_id\n",
    "    LEFT JOIN personal_cvd_pad_score pcv ON ph.person_id = pcv.person_id\n",
    "    LEFT JOIN xanthoma_score x ON ph.person_id = x.person_id\n",
    "    LEFT JOIN arcus_score a ON ph.person_id = a.person_id\n",
    "    WHERE ph.stage1_status = 'CASE'\n",
    ")\n",
    "\n",
    "SELECT \n",
    "    person_id,\n",
    "    index_date,\n",
    "    original_ldl_c,\n",
    "    adjusted_ldl_c,\n",
    "    total_dlcn_score,\n",
    "    ldl_points,\n",
    "    family_ascvd_points,\n",
    "    family_chol_points,\n",
    "    personal_chd_points,\n",
    "    personal_cvd_pad_points,\n",
    "    xanthoma_points,\n",
    "    arcus_points,\n",
    "    CASE \n",
    "        WHEN total_dlcn_score > 8 THEN 'DEFINITE_FH'\n",
    "        WHEN total_dlcn_score BETWEEN 6 AND 8 THEN 'PROBABLE_FH'\n",
    "        WHEN total_dlcn_score BETWEEN 3 AND 5 THEN 'POSSIBLE_FH'\n",
    "        WHEN total_dlcn_score <= 2 THEN 'UNLIKELY_FH'\n",
    "    END AS fh_classification,\n",
    "    CASE \n",
    "        WHEN total_dlcn_score > 8 THEN 'FH_CASE'\n",
    "        WHEN total_dlcn_score BETWEEN 6 AND 8 THEN 'FH_CASE'\n",
    "        WHEN total_dlcn_score <= 2 THEN 'FH_CONTROL'\n",
    "        ELSE 'FH_UNKNOWN'\n",
    "    END AS phenotype_status\n",
    "FROM dlcn_total_scores\n",
    "\n",
    "UNION ALL\n",
    "\n",
    "SELECT \n",
    "    person_id,\n",
    "    index_date,\n",
    "    original_ldl_c,\n",
    "    adjusted_ldl_c,\n",
    "    NULL AS total_dlcn_score,\n",
    "    NULL AS ldl_points,\n",
    "    NULL AS family_ascvd_points,\n",
    "    NULL AS family_chol_points,\n",
    "    NULL AS personal_chd_points,\n",
    "    NULL AS personal_cvd_pad_points,\n",
    "    NULL AS xanthoma_points,\n",
    "    NULL AS arcus_points,\n",
    "    'NOT_APPLICABLE' AS fh_classification,\n",
    "    'FH_CONTROL' AS phenotype_status\n",
    "FROM primary_hypercholesterolemia\n",
    "WHERE stage1_status = 'CONTROL'\n",
    "\n",
    "ORDER BY \n",
    "    CASE phenotype_status\n",
    "        WHEN 'FH_CASE' THEN 1\n",
    "        WHEN 'FH_UNKNOWN' THEN 2\n",
    "        WHEN 'FH_CONTROL' THEN 3\n",
    "    END,\n",
    "    total_dlcn_score DESC NULLS LAST;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": false,
     "catalog": "workspace_sdphenotypecore",
     "schema": "agd_flagship"
    }
   },
   "notebookName": "ex2_only_text__LLM2__FH.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}