{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "92d1ddb6-fa52-4f07-a321-92f3980efaee",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- Rule 1 (VUMC-specific database name): APPLIED\n",
    "-- Rule 4 (LOINC/RxNorm join): APPLIED\n",
    "-- Rule 3 (ICD code in *_source_value): APPLIED\n",
    "-- Rule 5 (free-text LIKE): NOT APPLICABLE\n",
    "-- Rule 6 (OR->UNION): NOT APPLICABLE\n",
    "-- Rule 7 (LEFT JOIN->UNION): NOT APPLICABLE\n",
    "-- Rule 8 (remove NLP): NOT APPLICABLE\n",
    "-- Rule 9 (missing concept): NOT APPLICABLE\n",
    "-- FIX: Rewrote rx CTE to avoid subqueries in FROM clause and use precomputed descendant_concept_ids for T2 and T1 drugs for Databricks SQL compatibility.\n",
    "-- FIX: Ensured all CTEs are properly closed and query structure is valid for Databricks SQL.\n",
    "\n",
    "CREATE TABLE workspace_sdphenotypecore.phenotype_llm_logic.ex2_only_text_LLM1_T2DM AS \n",
    "\n",
    "WITH loinc_concepts AS (\n",
    "  -- REVISED (was: SELECT * FROM concept WHERE vocabulary_id = 'LOINC')\n",
    "  SELECT concept_id, concept_code\n",
    "  FROM victr_sd.sd_omop_prod.concept\n",
    "  WHERE vocabulary_id = 'LOINC' AND concept_code IN ('1558-6','2339-0','2345-7','4548-4','17856-6','4549-2','17855-8')\n",
    "),\n",
    "\n",
    "rxnorm_concepts_t2 AS (\n",
    "  SELECT concept_id\n",
    "  FROM victr_sd.sd_omop_prod.concept\n",
    "  WHERE vocabulary_id = 'RxNorm' AND concept_code IN ('173','10633','2404','4821','217360','4815','25789','73044','274332','6809','84108','33738','72610','16681','30009','593411','60548')\n",
    "),\n",
    "\n",
    "rxnorm_concepts_t1 AS (\n",
    "  SELECT concept_id\n",
    "  FROM victr_sd.sd_omop_prod.concept\n",
    "  WHERE vocabulary_id = 'RxNorm' AND concept_code IN ('139825','274783','314684','352385','400008','51428','5856','86009','139953')\n",
    "),\n",
    "\n",
    "descendant_t2 AS (\n",
    "  -- Get all descendant_concept_ids for T2 drugs\n",
    "  SELECT descendant_concept_id\n",
    "  FROM victr_sd.sd_omop_prod.concept_ancestor\n",
    "  WHERE ancestor_concept_id IN (SELECT concept_id FROM rxnorm_concepts_t2)\n",
    "),\n",
    "\n",
    "descendant_t1 AS (\n",
    "  -- Get all descendant_concept_ids for T1 drugs\n",
    "  SELECT descendant_concept_id\n",
    "  FROM victr_sd.sd_omop_prod.concept_ancestor\n",
    "  WHERE ancestor_concept_id IN (SELECT concept_id FROM rxnorm_concepts_t1)\n",
    "),\n",
    "\n",
    "lab_flags AS (\n",
    "  SELECT  m.person_id,\n",
    "          MAX(CASE WHEN lc.concept_code = '1558-6' AND m.value_as_number >= 125 THEN 1 END) AS fast_case,\n",
    "          MAX(CASE WHEN lc.concept_code IN ('2339-0','2345-7') AND m.value_as_number > 200 THEN 1 END) AS rnd_case,\n",
    "          MAX(CASE WHEN lc.concept_code IN ('4548-4','17856-6','4549-2','17855-8') AND m.value_as_number >= 6.5 THEN 1 END) AS a1c_case,\n",
    "          MAX(CASE WHEN lc.concept_code = '1558-6' AND m.value_as_number >= 110 THEN 1 END) AS fast_ctrl,\n",
    "          MAX(CASE WHEN lc.concept_code IN ('2339-0','2345-7') AND m.value_as_number > 110 THEN 1 END) AS rnd_ctrl,\n",
    "          MAX(CASE WHEN lc.concept_code IN ('4548-4','17856-6','4549-2','17855-8') AND m.value_as_number >= 6.0 THEN 1 END) AS a1c_ctrl,\n",
    "          COUNT(DISTINCT CASE\n",
    "                 WHEN (\n",
    "                        (lc.concept_code = '1558-6' AND m.value_as_number >= 125) OR\n",
    "                        (lc.concept_code IN ('2339-0','2345-7') AND m.value_as_number > 200) OR\n",
    "                        (lc.concept_code IN ('4548-4','17856-6','4549-2','17855-8') AND m.value_as_number >= 6.5)\n",
    "                      )\n",
    "                 THEN m.measurement_date\n",
    "               END) AS abnl_case_dates\n",
    "  FROM   victr_sd.sd_omop_prod.measurement m\n",
    "         JOIN loinc_concepts lc ON m.measurement_concept_id = lc.concept_id\n",
    "  GROUP BY m.person_id\n",
    "),\n",
    "\n",
    "dx AS (\n",
    "  SELECT  c.person_id,\n",
    "    COUNT(DISTINCT CASE\n",
    "            WHEN LEFT(c.condition_source_value,4) = '250.' \n",
    "                 AND RIGHT(c.condition_source_value,1) IN ('0','2')\n",
    "                 AND c.condition_source_value NOT IN ('250.10','250.12')\n",
    "            THEN c.condition_start_date END)            AS dx_t2_cnt,\n",
    "    COUNT(DISTINCT CASE\n",
    "            WHEN LEFT(c.condition_source_value,4) = '250.'\n",
    "                 AND RIGHT(c.condition_source_value,1) IN ('0','2')\n",
    "                 AND c.condition_source_value NOT IN ('250.10','250.12')\n",
    "                 AND c.condition_type_concept_id IN (38000250,38000275)\n",
    "            THEN c.condition_start_date END)            AS dx_t2_phys_cnt,\n",
    "    COUNT(DISTINCT CASE\n",
    "            WHEN LEFT(c.condition_source_value,4) = '250.'\n",
    "                 AND RIGHT(c.condition_source_value,1) IN ('1','3')\n",
    "            THEN c.condition_start_date END)            AS dx_t1_cnt,\n",
    "    COUNT(DISTINCT CASE\n",
    "            WHEN c.condition_source_value LIKE '250.%'\n",
    "                 OR c.condition_source_value IN ('790.21','790.22','790.2',\n",
    "                                                 '790.29','648.8','648.80',\n",
    "                                                 '648.81','648.82','648.83',\n",
    "                                                 '648.84','648.0','648.00',\n",
    "                                                 '648.01','648.02','648.03',\n",
    "                                                 '648.04','791.5','277.7',\n",
    "                                                 'V18.0','V77.1')\n",
    "            THEN c.condition_start_date END)            AS dx_dm_any_cnt\n",
    "  FROM   victr_sd.sd_omop_prod.condition_occurrence c\n",
    "  GROUP BY c.person_id\n",
    "),\n",
    "\n",
    "rx AS (\n",
    "  SELECT d.person_id,\n",
    "         MAX(CASE WHEN d.drug_concept_id IN (SELECT descendant_concept_id FROM descendant_t2) THEN 1 ELSE 0 END) AS rx_t2,\n",
    "         MAX(CASE WHEN d.drug_concept_id IN (SELECT descendant_concept_id FROM descendant_t1) THEN 1 ELSE 0 END) AS rx_t1\n",
    "  FROM victr_sd.sd_omop_prod.drug_exposure d\n",
    "  GROUP BY d.person_id\n",
    "),\n",
    "\n",
    "supplies AS (\n",
    "  SELECT  de.person_id,\n",
    "          MAX(1) AS dm_supply_flag\n",
    "  FROM    victr_sd.sd_omop_prod.device_exposure de\n",
    "  WHERE   de.device_source_value IN (\n",
    "            '126958','412956','412959','637321','668291','668370','686655',\n",
    "            '692383','748611','880998','881056','751128','847187','847191',\n",
    "            '847197','847203','847207','847211','847230','847239','847252',\n",
    "            '847256','847259','847263','847278','847416','847417','806905',\n",
    "            '806903','408119')\n",
    "  GROUP BY de.person_id\n",
    "),\n",
    "\n",
    "fam_hist AS (\n",
    "  SELECT  o.person_id,\n",
    "          MAX(1) AS fam_hist_dm\n",
    "  FROM    victr_sd.sd_omop_prod.observation o\n",
    "  WHERE   o.observation_source_value = 'V18.0'\n",
    "  GROUP BY o.person_id\n",
    "),\n",
    "\n",
    "visits AS (\n",
    "  SELECT  v.person_id,\n",
    "          COUNT(DISTINCT v.visit_start_date) AS visit_cnt\n",
    "  FROM    victr_sd.sd_omop_prod.visit_occurrence v\n",
    "  WHERE   v.visit_concept_id = 9201\n",
    "  GROUP BY v.person_id\n",
    "),\n",
    "\n",
    "evidence AS (\n",
    "  SELECT  p.person_id,\n",
    "          COALESCE(lf.fast_case,0)        AS fast_case,\n",
    "          COALESCE(lf.rnd_case,0)         AS rnd_case,\n",
    "          COALESCE(lf.a1c_case,0)         AS a1c_case,\n",
    "          COALESCE(lf.fast_ctrl,0)        AS fast_ctrl,\n",
    "          COALESCE(lf.rnd_ctrl,0)         AS rnd_ctrl,\n",
    "          COALESCE(lf.a1c_ctrl,0)         AS a1c_ctrl,\n",
    "          COALESCE(lf.abnl_case_dates,0)  AS abnl_case_dates,\n",
    "          COALESCE(dx.dx_t2_cnt,0)        AS dx_t2_cnt,\n",
    "          COALESCE(dx.dx_t2_phys_cnt,0)   AS dx_t2_phys_cnt,\n",
    "          COALESCE(dx.dx_t1_cnt,0)        AS dx_t1_cnt,\n",
    "          COALESCE(dx.dx_dm_any_cnt,0)    AS dx_dm_any_cnt,\n",
    "          COALESCE(rx.rx_t2,0)            AS rx_t2,\n",
    "          COALESCE(rx.rx_t1,0)            AS rx_t1,\n",
    "          COALESCE(sp.dm_supply_flag,0)   AS dm_supply_flag,\n",
    "          COALESCE(fh.fam_hist_dm,0)      AS fam_hist_dm,\n",
    "          COALESCE(v.visit_cnt,0)         AS visit_cnt\n",
    "  FROM    victr_sd.sd_omop_prod.person p\n",
    "  LEFT JOIN lab_flags    lf  ON lf.person_id = p.person_id\n",
    "  LEFT JOIN dx           dx  ON dx.person_id = p.person_id\n",
    "  LEFT JOIN rx           rx  ON rx.person_id = p.person_id\n",
    "  LEFT JOIN supplies     sp  ON sp.person_id = p.person_id\n",
    "  LEFT JOIN fam_hist     fh  ON fh.person_id = p.person_id\n",
    "  LEFT JOIN visits       v   ON v.person_id = p.person_id\n",
    ")\n",
    "\n",
    "SELECT person_id,\n",
    "       CASE\n",
    "         WHEN dx_t1_cnt > 0 OR rx_t1 = 1                        THEN 0\n",
    "         WHEN ( dx_t2_phys_cnt >= 2                              -- Path 1\n",
    "                OR (dx_t2_cnt >= 1 AND rx_t2 = 1)                -- Path 2\n",
    "                OR (dx_t2_cnt >= 1 AND (fast_case=1 OR rnd_case=1 OR a1c_case=1)) -- Path 3\n",
    "                OR (rx_t2 = 1   AND (fast_case=1 OR rnd_case=1 OR a1c_case=1))    -- Path 4\n",
    "                OR (abnl_case_dates >= 2)                        -- Path 5\n",
    "              )\n",
    "              THEN 1\n",
    "         ELSE 0\n",
    "       END  AS is_t2dm_case,\n",
    "       CASE\n",
    "         WHEN visit_cnt < 1                                   THEN 0\n",
    "         WHEN dx_t1_cnt  > 0 OR dx_t2_cnt  > 0                THEN 0\n",
    "         WHEN dx_dm_any_cnt > 0                               THEN 0\n",
    "         WHEN rx_t1 = 1 OR rx_t2 = 1                          THEN 0\n",
    "         WHEN dm_supply_flag = 1                              THEN 0\n",
    "         WHEN (fast_ctrl=1 OR rnd_ctrl=1 OR a1c_ctrl=1)       THEN 0\n",
    "         WHEN fam_hist_dm = 1                                 THEN 0\n",
    "         ELSE 1\n",
    "       END  AS is_t2dm_control\n",
    "FROM evidence;"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace_sdphenotypecore",
     "schema": "agd_flagship"
    }
   },
   "notebookName": "ex2_only_text__LLM1__T2DM.sql.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}